version: '3.8'
services:
  app:
    image: mawakajaka/jdungeon-server:main
    restart: always
    environment:
      DEBUG: ${DEBUG}
      RUN_AS_SERVER: ${RUN_AS_SERVER}
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS}
      GATEWAY_SERVER_PORT: ${GATEWAY_SERVER_PORT}
      SERVER_MAP: ${SERVER_MAP}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_MAX_PEERS: ${SERVER_MAX_PEERS}
      SERVER_CRT: ${SERVER_CRT}
      SERVER_KEY: ${SERVER_KEY}
      DATABASE_BACKEND: ${DATABASE_BACKEND}
      POSTGRES_ADDRESS: ${POSTGRES_ADDRESS}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${SERVER_CRT}:${SERVER_CRT}
      - ${SERVER_KEY}:${SERVER_KEY}
    network_mode: "host"

