version: '3'
services:
  app:
    image: mawakajaka/jdungeon-website:v1.0.4
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ${CERT_PATH}:${CERT_PATH}
      - ${KEY_PATH}:${KEY_PATH}
    network_mode: "host"
