version: '3'
services:
  app:
    image: mawakajaka/jdungeon-website:v3.0.4
    restart: always
    environment:
      NODE_ENV: production
      CERT_PATH: ${CERT_PATH}
      KEY_PATH: ${KEY_PATH}
    volumes:
      - ${CERT_PATH}:${CERT_PATH}
      - ${KEY_PATH}:${KEY_PATH}
      - ./images:/home/app/node_docker/public/images
    network_mode: "host"
