version: '3.8'
services:
  app:
    image: mawakajaka/jdungeon-gateway:main
    restart: always
    environment:
      DEBUG: ${DEBUG}
      RUN_AS_GATEWAY: ${RUN_AS_SERVER}
      GATEWAY_CLIENT_PORT: ${GATEWAY_CLIENT_PORT}
      GATEWAY_CLIENT_MAX_PEERS: ${GATEWAY_CLIENT_MAX_PEERS}
      GATEWAY_CLIENT_CRT: ${GATEWAY_CLIENT_CRT}
      GATEWAY_CLIENT_KEY: ${GATEWAY_CLIENT_KEY}
      GATEWAY_SERVER_PORT: ${GATEWAY_SERVER_PORT}
      GATEWAY_SERVER_MAX_PEERS: ${GATEWAY_SERVER_MAX_PEERS}
      GATEWAY_SERVER_CRT: ${GATEWAY_SERVER_CRT}
      GATEWAY_SERVER_KEY: ${GATEWAY_SERVER_KEY}
      STARTER_SERVER: ${STARTER_SERVER}
      DATABASE_BACKEND: ${DATABASE_BACKEND}
      POSTGRES_ADDRESS: ${POSTGRES_ADDRESS}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ${GATEWAY_CLIENT_CRT}:${GATEWAY_CLIENT_CRT}
      - ${GATEWAY_CLIENT_KEY}:${GATEWAY_CLIENT_KEY}
    network_mode: "host"

