- name: Install GitHub repo and run docker-compose
  hosts: all
  become: true
  vars:
    dest_repo: /root/repos/jdungeon-level-server
  tasks:
    - name: Clone GitHub repository
      git:
        repo: git@github.com:jonathaneeckhout/jdungeon-level-server.git
        dest: '{{ dest_repo }}'
        version: v0.0.3
        force: yes

    - name: Copy .env file
      copy:
        src: './.env'
        dest: '{{ dest_repo }}/.env'

    - name: Copy game files
      copy:
        src: "{{ item.src }}"
        dest: "{{ dest_repo }}/build/{{ item.dest }}"
      with_items:
        - { src: "Jdungeon-level-server.pck", dest: "linux/" }
        - { src: "Jdungeon-level-server.x86_64", dest: "linux/" }

    - name: make file executable
      file:
        path: "{{ dest_repo }}/build/linux/Jdungeon-level-server.x86_64"
        mode: u+x

    - name: Install Docker and Docker Compose
      apt:
        name: ['docker.io', 'docker-compose']
        state: present

    - name: Remove previously installed containers
      command:
        cmd: docker-compose down --remove-orphans --rmi local
        chdir: '{{ dest_repo }}'

    - name: Build and start containers
      command:
        cmd: docker-compose up -d --force-recreate
        chdir: '{{ dest_repo }}'

    - name: Remove the .env file
      file:
        path: '{{ dest_repo }}/.env'
        state: absent
