- name: Install GitHub repo and run docker-compose
  hosts: all
  become: true
  tasks:
    - name: Clone GitHub repository
      git:
        repo: git@github.com:jonathaneeckhout/jdungeon-database.git
        dest: /root/repos/jdungeon-database
        version: v1.0.0
        force: yes
    
    - name: Copy .env file
      copy:
        src: ".env"
        dest: "/root/repos/jdungeon-database/.env"

    - name: Install Docker and Docker Compose
      apt:
        name: ['docker.io', 'docker-compose']
        state: present

    - name: Build and start containers
      command:
        cmd: docker-compose up -d
        chdir: /root/repos/jdungeon-database