- name: Install GitHub repo and run docker-compose
  hosts: all
  become: true
  vars:
    dest_repo: /root/repos/jdungeon-database
  tasks:
    - name: Copy docker-compose file file
      copy:
        src: './docker-compose/docker-compose-jdungeon-database.yml'
        dest: '{{ dest_repo }}/docker-compose.yml'

    - name: Install Docker and Docker Compose
      apt:
        name: ['docker.io', 'docker-compose']
        state: present

    - name: Remove previously installed containers
      command:
        cmd: docker-compose down --remove-orphans --rmi local
        chdir: '{{ dest_repo }}'

    - name: Build and start containers
      command:
        cmd: docker-compose up -d --force-recreate
        chdir: '{{ dest_repo }}'

    - name: Remove the .env file
      file:
        path: '{{ dest_repo }}/.env'
        state: absent
