- name: Install GitHub repo and run docker-compose
  hosts: all
  become: true
  vars:
    dest_repo: /root/repos/jdungeon-common-server
  tasks:
    - name: Clone GitHub repository
      git:
        repo: git@github.com:jonathaneeckhout/jdungeon-common-server.git
        dest: '{{ dest_repo }}'
        version: v0.0.6
        force: yes

    - name: Copy .env file
      copy:
        src: './.env'
        dest: '{{ dest_repo }}/.env'

    - name: Copy .init.json file
      copy:
        src: '.init.json'
        dest: '{{ dest_repo }}/.init.json'

    - name: Install Docker and Docker Compose
      apt:
        name: ['docker.io', 'docker-compose']
        state: present

    - name: Remove previously installed containers
      command:
        cmd: docker-compose down --remove-orphans --rmi local
        chdir: '{{ dest_repo }}'

    - name: Build and start containers
      command:
        cmd: docker-compose up -d --force-recreate
        chdir: '{{ dest_repo }}'

    - name: Remove the .env file
      file:
        path: '{{ dest_repo }}/.env'
        state: absent

    - name: Remove the .init.json file
      file:
        path: '{{ dest_repo }}/.init.json'
        state: absent