name: Deploy jdungeon-database
on: [push]
jobs:
  deploy-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy-jdungeon-database.yml
          # Optional, directory where playbooks live
          directory: ./playbooks/
          # Optional, SSH private key
          key: ${{secrets.SSH_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            jdungeon.org
          options: |
            --verbose